node {
  stage('login onto docker-hub') {
    withCredentials([[$class: 'UsernamePasswordMultiBinding', credentialsId: 'geor-docker-hub',
        usernameVariable: 'USERNAME', passwordVariable: 'PASSWORD']]) {
          sh "export DOCKER_API_VERSION=1.23 && docker login -u ${env.USERNAME} -p '${env.PASSWORD}'"
    }
  }

  stage('Preparation (git checkout & launching docker)') {
      checkout([
                  $class: 'GitSCM',
                  branches: [[ name: '*/master' ]],
                  doGenerateSubmoduleConfigurations: false,
                  extensions: [[
                    $class: 'SubmoduleOption',
                    disableSubmodules: false,
                    parentCredentials: false,
                    recursiveSubmodules: true,
                    reference: '',
                    trackingSubmodules: false
                  ]],
                  submoduleCfg: [],
                  userRemoteConfigs: [[
                    url: 'https://github.com/georchestra/cadastrapp.git'
                  ]]
                ])
  } // stage

  stage('build') {
    sh """mvn -B clean install"""
  } //stage

  stage('Create and Publish the debian package') {
      sh """mvn package deb:package deb:deploy -B                                      \
            -pl  cadastrapp -PdebianPackage -DskipTests                                \
            -Ddeb.repository.location=/var/www/packages.georchestra.org/htdocs/debian  \
            -Ddeb.reprepro.config=/var/www/packages.georchestra.org/htdocs/debian/conf \
            -Ddeb.repository.branch=master -Ddeb.package.version='\${project.version}+\${env.BUILD_NUMBER}'"""
  } // stage

} // node
