node {
  stage('login onto docker-hub') {
    withCredentials([[$class: 'UsernamePasswordMultiBinding', credentialsId: 'geor-docker-hub',
        usernameVariable: 'USERNAME', passwordVariable: 'PASSWORD']]) {
          sh "export DOCKER_API_VERSION=1.23 && docker login -u ${env.USERNAME} -p '${env.PASSWORD}'"
    }
  }

  // Pulling the docker builder image
  stage('docker pull the geOrchestra builder image') {
    sh 'docker pull georchestra/jenkins-builder:jdk8'
  }
  stage('build') {
    withDockerContainer(image: 'georchestra/jenkins-builder:jdk8', args: """--privileged -u 0:0   \
  -v /var/www/packages.georchestra.org/htdocs:/var/www/packages.georchestra.org/htdocs \
  -v /home/jenkins-tools/gnupg:/root/.gnupg""") {
      stage('Checking out the geOrchestra repository') {
        git url:'https://github.com/georchestra/georchestra.git', branch:"master"
        sh "git submodule update --init --recursive"
        // This is specific to the geOrchestra build env and is probably not needed
        sh 'echo "172.16.42.42 packages.georchestra.org" >> /etc/hosts'
        sh 'service docker start'
      }
      stage('configure georchestra docker-hub account / login on docker-hub') {
        withCredentials([[$class: 'UsernamePasswordMultiBinding', credentialsId: 'geor-docker-hub',
              usernameVariable: 'USERNAME', passwordVariable: 'PASSWORD']]) {
            def configXmlStr = """<settings xmlns="http://maven.apache.org/SETTINGS/1.0.0"
              xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
              xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0
              http://maven.apache.org/xsd/settings-1.0.0.xsd">
                <servers>
                  <server>
                    <id>docker-hub</id>
                    <username>USERNAME</username>
                    <password>PASSWORD</password>
                    <configuration>
                      <email>psc@georchestra.org</email>
                    </configuration>
                  </server>
                </servers>
              </settings>""".replaceAll("USERNAME", env.USERNAME).replaceAll("PASSWORD", env.PASSWORD)
            sh "echo '${configXmlStr}' > /config.xml"
            sh "export DOCKER_API_VERSION=1.23 && docker login -u ${env.USERNAME} -p '${env.PASSWORD}'"
        }
      }
      stage('build mandatory modules') {
        sh """mvn clean install -B -Dmaven.repo.local=./.m2_repo -fn --non-recursive"""
        sh """mvn clean install -B -Dmaven.repo.local=./.m2_repo -fn -pl config"""
        sh """mvn clean install -B -Dmaven.repo.local=./.m2_repo -fn -pl commons,epsg-extension,ogc-server-statistics"""
      }
      stage('build / refresh geoserver & geonetwork artifacts') {
        sh """mvn clean install  -B -Dmaven.repo.local=./.m2_repo -f geonetwork/pom.xml -DskipTests"""
        sh """mvn clean install  -B -Dmaven.repo.local=./.m2_repo -f geoserver/pom.xml -DskipTests"""
      }
      stage('build / publish geOr images') {
        sh """mvn clean package docker:build docker:push  -B -Dmaven.repo.local=./.m2_repo -s /config.xml -Pdocker -DskipTests -pl atlas,extractorapp,security-proxy,mapfishapp"""
        sh """mvn clean package docker:build docker:push  -B -Dmaven.repo.local=./.m2_repo -s /config.xml -Pdocker -DskipTests -pl header,ldapadmin,analytics \
                -DdockerImageName='georchestra/\${project.artifactId}:latest'"""

        // then build the other images
        sh """mvn clean package docker:build docker:push  -B -Dmaven.repo.local=./.m2_repo -s /config.xml -Pdocker -DskipTests -pl cas-server-webapp -DdockerImageName=georchestra/cas:latest"""
        sh """mvn clean package docker:build docker:push  -B -Dmaven.repo.local=./.m2_repo -s /config.xml -Pdocker -DskipTests -pl geoserver/webapp -DdockerImageName=georchestra/geoserver:latest"""
        sh """mvn clean package docker:build docker:push  -B -Dmaven.repo.local=./.m2_repo -s /config.xml -Pdocker -DskipTests -pl geonetwork/web -DdockerImageName=georchestra/geonetwork:341-latest"""
        sh """mvn clean package docker:build docker:push  -B -Dmaven.repo.local=./.m2_repo -s /config.xml -Pdocker -DskipTests -pl geowebcache-webapp -DdockerImageName=georchestra/geowebcache:latest"""
      } // stage
      stage("Saving tests results") {
        // this requires the Junit Jenkins module
        junit '**/target/surefire-reports/TEST-*.xml'
      } // stage
      stage('Spawning ansible remotely onto sdi.g.o') {
        sshagent(["ansible-docker-trigger-key"]) {
          sh "ssh -oStrictHostKeyChecking=no root@172.16.42.42"
        } // sshagent
      } // stage
    } // withDocker
  } // stage
} // node
