node {
  // Pulling the docker builder image
  stage('docker pull the geOrchestra builder image') {
    sh 'docker pull georchestra/jenkins-builder'
  }
  stage('build') {
    withDockerContainer(image: 'georchestra/jenkins-builder', args: """--privileged -u 0:0   \
  -v /var/www/packages.georchestra.org/htdocs:/var/www/packages.georchestra.org/htdocs \
  -v /home/jenkins-tools/gnupg:/root/.gnupg -v /home/jenkins-tools/m2_master:/root/.m2""") {
      stage('Checking out the geOrchestra repository') {
        git url:'https://github.com/georchestra/georchestra.git', branch:"master"
        sh "git submodule update --init --recursive"
        sh 'service docker start'
      }
      stage('configure georchestra docker-hub account / login on docker-hub') {
        withCredentials([[$class: 'UsernamePasswordMultiBinding', credentialsId: 'geor-docker-hub',
              usernameVariable: 'USERNAME', passwordVariable: 'PASSWORD']]) {
            def configXmlStr = """<settings xmlns="http://maven.apache.org/SETTINGS/1.0.0"
              xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
              xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0
              http://maven.apache.org/xsd/settings-1.0.0.xsd">
                <servers>
                  <server>
                    <id>docker-hub</id>
                    <username>USERNAME</username>
                    <password>PASSWORD</password>
                    <configuration>
                      <email>psc@georchestra.org</email>
                    </configuration>
                  </server>
                </servers>
              </settings>""".replaceAll("USERNAME", env.USERNAME).replaceAll("PASSWORD", env.PASSWORD)
            sh "echo '${configXmlStr}' > /config.xml"
        }
      }
      stage('build mandatory modules') {
        sh """mvn clean install -fn --non-recursive"""
        sh """mvn clean install -fn -pl config"""
        sh """mvn clean install -fn -pl commons,epsg-extension,ogc-server-statistics"""
      }
      stage('build / refresh geoserver & geonetwork artifacts') {
        sh """mvn clean install -f geonetwork/pom.xml -DskipTests"""
        sh """mvn clean install -pl geoserver -DskipTests"""
      }
      stage('build / publish geOr images') {
        sh """mvn clean package docker:build docker:push -s /config.xml -Pdocker -DskipTests -pl atlas,extractorapp,security-proxy,mapfishapp"""
        sh """mvn clean package docker:build docker:push -s /config.xml -Pdocker -DskipTests -pl header,ldapadmin,analytics,catalogapp,downloadform \
                -DdockerImageName='georchestra/\${project.artifactId}:latest'"""

        // then build the other images
        sh """mvn clean package docker:build docker:push -s /config.xml -Pdocker -DskipTests -pl cas-server-webapp -DdockerImageName=georchestra/cas:latest"""
        sh """mvn clean package docker:build docker:push -s /config.xml -Pdocker -DskipTests -pl geoserver/webapp -DdockerImageName=georchestra/geoserver:latest"""
        sh """mvn clean package docker:build docker:push -s /config.xml -Pdocker -DskipTests -pl geonetwork/web -DdockerImageName=georchestra/geonetwork:3-latest"""
        sh """mvn clean package docker:build docker:push -s /config.xml -Pdocker -DskipTests -pl geowebcache-webapp -DdockerImageName=georchestra/geowebcache:latest"""
      } // stage
      stage('build postgresql geOr image') {
        sh """cd ${WORKSPACE}/postgresql                    && \
              docker pull postgres:9.4                      && \
              docker build -t georchestra/database:latest . && \
              docker push georchestra/database:latest"""
      } //stage
      stage("build ldap geOr image") {
        sh """cd ${WORKSPACE}/ldap                          && \
              docker pull dinkel/openldap                   && \
              docker build -t georchestra/ldap:latest .     && \
              docker push georchestra/ldap:latest"""
      } // stage
      stage("build ssh_data geOr image") {
        sh """cd ${WORKSPACE}/docker/ssh_data               &&  \
              docker pull debian:jessie                     &&  \
              docker build -t georchestra/ssh_data:latest . &&  \
              docker push georchestra/ssh_data:latest"""
      } // stage
      stage("Saving tests results") {
        // this requires the Junit Jenkins module
        junit '**/target/surefire-reports/TEST-*.xml'
      } // stage
    } // withDocker
  } // stage
} // node
