node {

  stage('Configuring things up & checking out the geOrchestra repository') {

    checkout([$class: 'GitSCM',
      branches: [[name: '*/master']],
      doGenerateSubmoduleConfigurations: false,
      extensions: [[ $class: 'SubmoduleOption',
        disableSubmodules: false,
        parentCredentials: false,
        recursiveSubmodules: true,
        reference: '',
        trackingSubmodules: false]],
      submoduleCfg: [],
      userRemoteConfigs: [[url: 'https://github.com/georchestra/georchestra.git']]
    ])
  }
  stage('build mandatory modules') {
    sh """mvn clean install -B -Dmaven.repo.local=./.m2_repo --non-recursive"""
    sh """mvn clean install -B -Dmaven.repo.local=./.m2_repo -pl commons,ogc-server-statistics"""
  }
  stage('build / refresh geoserver & geonetwork artifacts') {
    sh """mvn clean install -U -B -Dmaven.repo.local=./.m2_repo -f geonetwork/pom.xml"""
    sh """mvn clean install -U -B -Dmaven.repo.local=./.m2_repo -f geoserver/pom.xml"""
  }
  stage("build debian packages") {
    sh """mvn clean package deb:package deb:deploy -B -Dmaven.repo.local=./.m2_repo                                                                      \
          -pl atlas,cas-server-webapp,security-proxy,header,mapfishapp,extractorapp,analytics,geoserver/webapp,console,geonetwork/web,geowebcache-webapp \
          -PdebianPackage                                                                                                                                \
          -Ddeb.repository.location=/var/www/packages.georchestra.org/htdocs/debian                                                                      \
          -Ddeb.reprepro.config=/var/www/packages.georchestra.org/htdocs/debian/conf                                                                     \
          -Ddeb.repository.branch=master -Ddeb.package.version='\${project.version}+\${env.BUILD_NUMBER}'"""
  } // stage

  stage('deploying onto sdi.g.o') {
      sshagent(["ansible-trigger-key"]) {
          sh "ssh -oStrictHostKeyChecking=no root@172.16.42.42"
      } // sshagent
  } // stage
} // node
