node {
  stage('login onto docker-hub') {
    withCredentials([[$class: 'UsernamePasswordMultiBinding', credentialsId: 'geor-docker-hub',
        usernameVariable: 'USERNAME', passwordVariable: 'PASSWORD']]) {
          sh "export DOCKER_API_VERSION=1.23 && docker login -u ${env.USERNAME} -p '${env.PASSWORD}'"
    }
  }

  // Pulling the docker builder image
  stage('docker pull the geOrchestra builder image') {
    sh 'docker pull georchestra/jenkins-builder:jdk8'
  }
  // blocks to be executed in parallel
  stage('spawning builder') {
    withDockerContainer(image: 'georchestra/jenkins-builder:jdk8', args: """--privileged -u 0:0   \
  -v /var/www/packages.georchestra.org/htdocs:/var/www/packages.georchestra.org/htdocs \
  -v /home/jenkins-tools/gnupg:/root/.gnupg""") {

      stage('Configuring things up & checking out the geOrchestra repository') {
        git url:'https://github.com/georchestra/georchestra.git', branch:"master"
        sh "git config --global user.email 'psc@georchestra.org'"
        sh "git config --global user.name 'geOrchestra PSC'"
        sh "git submodule update --init --recursive"
        // This is specific to the geOrchestra build env and is probably not needed
        sh 'echo "172.16.42.42 packages.georchestra.org" >> /etc/hosts'
        sh 'mkdir -p ~/.m2/'
        sh """echo '<settings><mirrors><mirror><id>artifactory</id><mirrorOf>*</mirrorOf><url>https://packages.georchestra.org/artifactory/maven</url></mirror></mirrors></settings>' > ~/.m2/settings.xml"""
        sh 'service docker start'
      }
      stage('build mandatory modules') {
        sh """mvn clean install -B -Dmaven.repo.local=./.m2_repo -fn --non-recursive"""
        sh """mvn clean install -B -Dmaven.repo.local=./.m2_repo -pl config -fn"""
        sh """mvn clean install -B -Dmaven.repo.local=./.m2_repo -fn -DskipTests -pl commons,ogc-server-statistics"""
      }
      stage('build / refresh geoserver & geonetwork artifacts') {
        sh """mvn clean install -B -Dmaven.repo.local=./.m2_repo -f geonetwork/pom.xml -DskipTests"""
        sh """mvn clean install -B -Dmaven.repo.local=./.m2_repo -f geoserver/pom.xml -DskipTests"""
      }
      stage("build artifacts") {
        sh """mvn package -B -Dmaven.repo.local=./.m2_repo                                                                                                    \
              -pl atlas,cas-server-webapp,security-proxy,header,mapfishapp,extractorapp,analytics,geoserver/webapp,console,geonetwork/web,geowebcache-webapp  \
              -DskipTests"""
      } // stage
      stage("Publishing artifacts") {
        withCredentials([string(credentialsId: 'github-token', variable: 'ghToken')]) {
          sh "mvn deploy -Dregistry=https://maven.pkg.github.com/georchestra -DaltDeploymentRepository='releaseRepository::default::https://maven.pkg.github.com/georchestra'  -Dtoken=${ghToken}"
        }
        sh "mkdir -p /var/www/packages.georchestra.org/htdocs/wars-master"
        sh "rm -f /var/www/packages.georchestra.org/htdocs/wars-master/*.war"
        sh "cp **/target/*.war geonetwork/web/target/*.war geoserver/webapp/target/*.war /var/www/packages.georchestra.org/htdocs/wars-master/"
      }
    } // withDocker
  } // stage
} // node
